#PS1='%F{86;1}[%B%~%b]%f %F{82;1}%B⮞ %b%f '
#PS1='%F{82;1}%B⮞ %b%f %F{86;1}[%B%~%b]%f '
PS1='%F{green}%B%n@%m%f:%F{blue}%~ $%f%b '
source $HOME/.config/shell/profile
source $HOME/.config/shell/alias
source $HOME/.config/shell/export

#printf "  Akash" | figlet -f ~/.config/fonts/mono12.tlf | lolcat 
#chafa ~/.local/share/images/india_flag.jpg

