#!/bin/bash

if [ $# -eq 0 ]; then
  if [[ -t 0 ]]; then
    echo "Usage: <command> | $0"
    echo "Hint: Share text to paste.rs (pastebin type)."
    exit
  else
    #cat | curl -s -F 'f:1=<-' ix.io | tee /dev/tty | xclip -sel -c
    #cat | curl -s -F 'f:1=<-' ix.io
    cat | curl --data-binary @- https://paste.rs/
    exit
  fi
else
  echo "$*" | curl --data-binary @- https://paste.rs/
  exit 0
fi
