# Windows Rules
windowrule = workspace 3, ^(code-oss)$
windowrule = workspace 1, ^(Arduino IDE)$
windowrule = workspace 2, ^(firefox)$
windowrule = workspace 3, ^(org.gnome.Nautilus)$
windowrule = workspace 3, ^(thunar)$
windowrule = workspace 5, ^(org.telegram.desktop)$
windowrule = workspace 4, ^(blender)$
windowrule = workspace 4, ^(Gimp-2.10)$
windowrule = workspace 4, ^(org.freecad.FreeCAD)$
windowrule = workspace 4, ^(com.github.xournalpp.xournalpp)$
windowrule = workspace 4, ^(librecad)$
windowrule = workspace 4, ^(libreoffice-writer)$
windowrule = workspace 4, ^(libreoffice-calc)$
windowrule = workspace 4, ^(libreoffice-math)$
windowrule = workspace 4, ^(libreoffice-impress)$
windowrule = workspace 4, ^(libreoffice-draw)$
windowrule = workspace 4, ^(libreoffice-base)$
windowrule = workspace 6, ^(gnome-boxes)$



windowrule = float,^(pavucontrol)$
windowrule = pin,^(pavucontrol)$
windowrule = size 900 500,^(pavucontrol)$

windowrule = float,^(blueman-manager)$
windowrule = pin,^(blueman-manager)$
windowrule = size 900 500,^(blueman-manager)$

windowrule = float,^(imv)$
windowrule = pin,^(imv)$
windowrule = size 1600 900,^(imv)$

windowrule = float,^(zenity)$
windowrule = pin,^(zenity)$
layerrule = blur,^(eww-blur)$
layerrule = blur,^(gtk-layer-shell)$
