function get_local_ip() {
	ip addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
}


PS1='%F{yellow}%B%n@$(get_local_ip)%f:%F{blue}%~ $%f%b '
sshd -p 2222

export PATH="$HOME/.local/bin/:$PATH"

source ~/.config/alias

# Comment of '#'
setopt interactivecomments

## Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
#_comp_options+=(globdots)		# Include hidden files.
bindkey '^[[Z' reverse-menu-complete # Reverse menu select (shift+tab)

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

# Key Binding
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[l" forward-char
bindkey "^[h" backward-char
bindkey "^[[Zl" forward-word  #shift+l
bindkey "^[[Zh" backward-word
bindkey  "^[[3~"  delete-char
bindkey -s '^O' "cd ..\n"

## Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^n' edit-command-line

## Git 
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
RPROMPT='${vcs_info_msg_0_}'
zstyle ':vcs_info:git:*' formats '%K{green}%B  %b %k'
