#!/bin/bash
#value=5
#pkexec xfpm-power-backlight-helper --set-brightness 7200
if [[ -z $2 ]]; then  
  value=5
else
  value=$2
fi


if [[ $1 == "+" ]]; then
   light -a $value
else
  light -u $value
fi
curr_vol=$(light -g)
notify-send -r 2 -h int:value:$curr_vol "brightness $curr_vol"


